### ISSUE TITLE
Synchronous?

### ISSUE THREAD

**Issue by mattdesl** [wooorm/mdast-util-visit#1]
Is it safe to assume this is synchronous and will remain so? Might be helpful to add this in readme somewhere. :smile:

e.g.

```js
  var defs = []
  visit(ast, function (node, index, parent) {
    if (node.type === 'definition') {
      defs.push(node)
    }
  })
  console.log(defs)
```

**Comment by wooorm** [comment]
Thanks, done! Didn’t opt for the example though, I like how it’s currently 😉

**Comment by mattdesl** [comment]
Great, thanks. :+1: 

Using mdast with [gh-md-urls](https://github.com/mattdesl/gh-md-urls) and [gh-readme-scrape](https://github.com/mattdesl/gh-readme-scrape) -- super easy!
